### ISSUE TITLE
pw2p

### ISSUE THREAD

**Issue by mplussier** [eeveetza/p452#5]
Hi,
I just want to mention that there is a number of issues with the pw2p function in the pw2p.m file.

- Line 28: the absolute value of phi should be used.
- Lines 29 and 31: phi should be converted to radians.
- Line 34: should be log10(GL) instead of log(GL).
- Line 35: should add parentheses so to have (0.816 + 0.078*omega).
- Also the recommendation mentions that the value of p must be limited so that 12p >= pw. I think this should be added to the function.

Hope this helps, best regards.

**Comment by eeveetza** [comment]
Thank you for these corrections. They are now included in the dev branch and will be eventually included in the new version of the main branch. Hopefully the issue can be closed now.

**Comment by mplussier** [comment]
Looks good, thanks for the quick response, closing the issue.
